version: "3.8"
services:
  postgres-db:
    image: postgres:15
    container_name: ai_scribe_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: aiscribe_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: ai_scribe_adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres-db

volumes:
  pgdata:
